### ISSUE TITLE
Release planning for v2

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/the-littlest-jupyterhub#991]
I'd like to work towards a v2 release with jupyterhub 5 and oauthenticator 17.

## Todo

- #990
- Test and verify function against ubuntu 24.04
  - [x] Integration tests
  - [x] Unit tests: https://github.com/jupyterhub/the-littlest-jupyterhub/pull/993
- [x] Transition to jupyterhub 5 (#989)
- [x] Transition to oauthenticator 17
  - [x] Note that `oauthenticator[azuread]>=16.0.4,<17` is installed, but we no longer need to specify `azuread` I think. Look  it up in oauthenticator.
  - #992 
- Consider getting a release out for:
  - [x] [jupyterhub-systemdspawner](https://github.com/jupyterhub/systemdspawner)>=1.0.1,<2
    - [x] Ensure tests for jupyterhub 5 etc pass and refresh CI system things
      https://github.com/jupyterhub/systemdspawner/pull/143
    - [x] No merged PRs, not aiming for a release.
  - [x] [jupyterhub-firstuseauthenticator](https://github.com/jupyterhub/firstuseauthenticator)>=1.0.0,<2
    - [x] Ensure tests for jupyterhub 5 etc pass and refresh CI system things
      https://github.com/jupyterhub/firstuseauthenticator/pull/57
      https://github.com/jupyterhub/firstuseauthenticator/pull/56
    - [x] Make release, a PR related to jupyterhub 5 is merged.
      https://github.com/jupyterhub/firstuseauthenticator/pull/58
  - [x] [jupyterhub-nativeauthenticator](https://github.com/jupyterhub/nativeauthenticator)>=1.2.0,<2
    - [x] Ensure tests for jupyterhub 5 etc pass and refresh CI system things
      https://github.com/jupyterhub/nativeauthenticator/pull/274
    - Fix a bug: https://github.com/jupyterhub/nativeauthenticator/pull/275
    - [x] Make release, things have happened since last.
      
  - [x] [jupyterhub-ldapauthenticator](https://github.com/jupyterhub/ldapauthenticator)>=1.3.2,<2
    - [x] Ensure tests for jupyterhub 5 etc pass and refresh CI system things
      https://github.com/jupyterhub/ldapauthenticator/pull/244
      https://github.com/jupyterhub/ldapauthenticator/pull/245
      https://github.com/jupyterhub/ldapauthenticator/issues/246
    - [x] Make release of v2.0.0
      - https://github.com/jupyterhub/ldapauthenticator/pull/272
      - https://github.com/jupyterhub/ldapauthenticator/pull/285
      - https://github.com/jupyterhub/ldapauthenticator/issues/220
  - [x] [jupyterhub-tmpauthenticator](https://github.com/jupyterhub/tmpauthenticator)>=1.0.0,<2
    - [x] Ensure tests for jupyterhub 5 etc pass and refresh CI system things
      https://github.com/jupyterhub/tmpauthenticator/pull/65
    - [x] No release needed, nothing merged of relevance.
  - [x] [jupyterhub-idle-culler](https://github.com/jupyterhub/jupyterhub-idle-culler)>=1.2.1,<2
    - [x] Ensure tests for jupyterhub 5 etc pass and refresh CI system things
      https://github.com/jupyterhub/jupyterhub-idle-culler/pull/80
    - [x] Make release, a new feature was added.
      https://github.com/jupyterhub/jupyterhub-idle-culler/pull/81
- [x] Do a final 2.0.0 release of ldapauthenticator and bump here
- [x] Update lower bounds on all stuff above
- Consider working the following open PRs through the finish line or closing them
  - [x] #414
  - [x] #784
  - [x] #942
  - [x] #976
- Update to use traefik-proxy v2
  https://github.com/jupyterhub/the-littlest-jupyterhub/issues/996
- [x] Add https://github.com/jupyterhub/the-littlest-jupyterhub/pull/1003 to the changelog, which wasn't captured in the 2.0.0b1 release
- [x] make changelog link to upgrade docs

**Comment by minrk** [comment]
24.04 is aleady in the test matrix, and JupyterHub 5 is done in #989

**Comment by minrk** [comment]
I want to try to put a lot less pressure on other projects when we prepare a release like this. I feel strongly that we should _at most_ check if a project is "due" for a release and do no more coordination than that. Deciding that a distribution is ready for release should ideally not _create_ time-pressured work in other repos. If they aren't ready or approximately ready to release when it's time to make a distro release, they shouldn't be in the distro release.

@consideRatio's been doing a lot of great work refreshing projects like ldapauthenticator, but I also want to make sure that work like that is not considered part of the release process for tljh or z2jh (i.e. I'm definitely not saying the work shouldn't be done, but it shouldn't be _expected_ when another project is preparing a release, and typically shouldn't block a downstream release).

**Comment by consideRatio** [comment]
I went for 2.0.0b1

https://discourse.jupyter.org/t/the-littlest-jupyterhub-tljh-distribution-2-0-0b1-beta-1-is-out/28822

**Comment by consideRatio** [comment]
Argh.. I think there now is two separate new failures.

1. jupyterhub 5.2.0 led to failures in the test suite
2. upgrading from 0.2.0 may have started failing for another reason not clear, but I figure its related to installing 0.2.0 with its dependencies now no longer works, but that it doesn't rule out one can upgrade from it still

**Comment by consideRatio** [comment]
JupyterHub 5.2.0 now functions, with systemdspawner 1.0.2 bugfix release, fixed in https://github.com/jupyterhub/the-littlest-jupyterhub/pull/1008.
